Default: &defaults
  database: YesodDemo.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: YesodDemo_test.sqlite3
  <<: *defaults

Staging:
  database: YesodDemo_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: YesodDemo_production.sqlite3
  poolsize: 100
  <<: *defaults
